---
title: "Open Source License"
bibliography: ../quarto_site/references.bib
---

This repository is licensed under the BSD 3-Clause License.

::: {.callout-note appearance="minimal" collapse=true}

## View license

{{< include  ../LICENSE >}}

:::

This is aligned with the original study, who shared their code under BSD 3-Clause License.

::: {.callout-note appearance="minimal" collapse=true}

## View license

{{< include  ../original_study/charm/LICENSE >}}

:::

The original study was published in the journal "IEEE Xplore". The copyright is retained by this journal. Open access versions are available with [Brunel University Research Archive](https://bura.brunel.ac.uk/handle/2438/25912) and [UCL Discovery](https://discovery.ucl.ac.uk/id/eprint/10187277/), but these are just for personal use, as in the statement below:

::: {.callout-note appearance="minimal" collapse=true}

## View copyright statement

"Copyright © 2022 IEEE. Personal use of this material is permitted. Permission from IEEE must be obtained for all other uses, in any current or future media, including reprinting/republishing this material for advertising or promotional purposes, creating new collective works, for resale or redistribution to servers or lists, or reuse of any copyrighted component of this work in other works."

<https://bura.brunel.ac.uk/handle/2438/25912>

:::