---
title: "Reflections"
---

This page contains reflections on the facilitators and barriers to this reproduction, as well as a full list of the troubleshooting steps taken to reproduce this work.

## What would have helped facilitate this reproduction?

**Figure** - provide code to produce the figure

**Note:** Although not needed for the reproduction itself, when I tried to amend the **name and location of the csv file** output the model for use in tests, this was very tricky to do as it was hard coded into the scripts and I found difficult to amend due to how the model is run and set up.

## What did help facilitate this reproduction?

**README** - clear README with instructions on how to run the model.

**Data dictionary for input parameters** - although I didn't need this, this would have been great if I needed to change the input parameters at all.

**Environment** - stated version of Python and provided requirements file (simpy, with version given in the app repository).

**Simple results spreadsheet** - the layout of the results spreadsheet was simple, understandable and easy to read, making it easy to adapt into figures

**Simple figures** - the figures were simply (just means and CI which are already calculated).

## Full list of troubleshooting steps

::: {.callout-note appearance="minimal" collapse=false}
## View list

Troubleshooting steps are grouped by theme, and the day these occurred is given in brackets at the end of each bullet.

### Figure

* No code provided to produce figure, so wrote this from scratch (2-3)

:::