---
title: "Scope"
echo: False
bibliography: ../quarto_site/references.bib
---

This page outlines the parts of the journal article (@anagnostou_facs-charm_2022) which we will attempt to reproduce.

As the copyright of the article belongs to the journal (without permissions to freely share images from the article), I have simply provided quotations from the figure captions below. You will need to navigate to the original paper to view the items.

## Within scope

::: {.callout-note appearance="minimal" collapse=false}

## Figure 3

Figure 3. "CHARM example output. Graphs a, b and c show the mean value of elective beds capacity and availability (a) and 95% confidence intervals (b) and (c), respectively. Graphs d, e and f show the mean value of COVID-19 beds capacity and availability (d) and 95% confidence intervals (e) and (f), respectively." @anagnostou_facs-charm_2022

:::

## Outside scope

::: {.callout-note appearance="minimal" collapse=false}

## Figure 1

Output from FACS (agent-based simulation).

Figure 1. "FACS example output daily cases (a) and daily hospitalizations (b)". @anagnostou_facs-charm_2022

:::

::: {.callout-note appearance="minimal" collapse=false}

## Figure 2

Figure 2. "CHARM patient flow diagram". @anagnostou_facs-charm_2022

:::

::: {.callout-note appearance="minimal" collapse=false}

## Table 1

Table 1. "CHARM example input parameters". @anagnostou_facs-charm_2022

:::

::: {.callout-note appearance="minimal" collapse=false}

## Figure 4

Figure 4. "Hybrid FACS-CHARM data exchange". @anagnostou_facs-charm_2022

:::

::: {.callout-note appearance="minimal" collapse=false}

## Figure 5

Figure 5. "CHARM (a) and FACS (b) dashboards". @anagnostou_facs-charm_2022

:::